source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

def shared_pods
	pod 'SDWebImage'
	pod 'Alamofire'
    pod 'AlamofireImage'
    pod 'SwiftyJSON'
#    pod 'SwiftString'
	pod 'DeviceKit'
    pod 'CryptoSwift'
    pod 'HanekeSwift', :git => 'https://github.com/jasonnoahchoi/HanekeSwift', :branch => 'swift3'
end

	 
target 'TestCoreLibrary' do
	shared_pods
end

target 'TestCoreLibraryTests' do
	shared_pods
end

